# .depguard.yml
packages:
  main:
    allow:
      - github.com/spf13/cobra
      - github.com/go-redis/redis/v8 
  github.com/go-redis/redis/v8:
    allow: true 
  github.com/Dmitry-Tsarkov/brute-force-service-gwrk/api:
    allow: true
  github.com/Dmitry-Tsarkov/brute-force-service-gwrk/internal/redisclient:
    allow: true
  github.com/stretchr/testify/assert:
    allow: true
