name: CI Pipeline

on:
  push:
    branches:
      - main
      - evaluation
  pull_request:
    branches:
      - main
      - evaluation

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Verify go.mod status
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0  
    
      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: go test -v ./...

      - name: Build the project
        run: go build -v ./...

      - name: Upload test results if tests fail
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: .
